// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import frc.robot.commands.*;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    public XboxController xbox1; // the drive controller // input 0 on driver station
    private Button xbox1LeftStick;
    private Button xbox1RightStick;
    private Button xbox1LBumper;
    private Button xbox1RBumper;
    private Button xbox1Start;
    private Button xbox1Back;
    private Button xbox1X;
    private Button xbox1Y;
    private Button xbox1B;
    private Button xbox1A;

    // private XboxController xbox2; // the game mech controller // input 1 on driver station
    // private Button xbox2LeftStick;
    // private Button xbox2RightStick;
    // private Button xbox2LBumper;
    // private Button xbox2RBumper;
    // private Button xbox2Start;
    // private Button xbox2Back;
    // private Button xbox2X;
    // private Button xbox2Y;
    // private Button xbox2B;
    // private Button xbox2A;

    public OI() {
        // create our buttons
        xbox1 = new XboxController(0);

        xbox1A = new JoystickButton(xbox1, 1);
        xbox1B = new JoystickButton(xbox1, 2);
        xbox1X = new JoystickButton(xbox1, 3);
        xbox1Y = new JoystickButton(xbox1, 4);
        xbox1LBumper = new JoystickButton(xbox1, 5);
        xbox1RBumper = new JoystickButton(xbox1, 6);
        xbox1Back = new JoystickButton(xbox1, 7);
        xbox1Start = new JoystickButton(xbox1, 8);
        xbox1LeftStick = new JoystickButton(xbox1, 9);
        xbox1RightStick = new JoystickButton(xbox1, 10);

        // xbox2 = new XboxController(1);

        // xbox2A = new JoystickButton(xbox2, 1);
        // xbox2B = new JoystickButton(xbox2, 2);
        // xbox2X = new JoystickButton(xbox2, 3);
        // xbox2Y = new JoystickButton(xbox2, 4);
        // xbox2LBumper = new JoystickButton(xbox2, 5);
        // xbox2RBumper = new JoystickButton(xbox2, 6);
        // xbox2Back = new JoystickButton(xbox2, 7);
        // xbox2Start = new JoystickButton(xbox2, 8);
        // xbox2LeftStick = new JoystickButton(xbox2, 9);
        // xbox2RightStick = new JoystickButton(xbox2, 10);

        // Drive Controller Command Mapping

        xbox1X.whenPressed(new SwitchFront());
        xbox1Back.whenPressed(new ToggleTalonMode());
        xbox1RBumper.whileHeld(new ArcDrive2());
        xbox1RBumper.whenReleased(new SetTalonMode("brake"));
        xbox1LBumper.whenPressed(new ToggleDebug());

        //Pathfinder
        xbox1Y.whenPressed(new PathfinderRun());
        xbox1B.whenPressed(new OpenLoopDrive()); // will interrupt PathfinderRun

        // Mech Controller Command Mapping

        /* Old Game Mech Mapping From Heartland */
        // xbox2Y.whenPressed(new GameMechClose());
        // xbox2B.whenPressed(new GameMechOpen());
        // xbox2A.whenPressed(new FlyWheelSetSpeed(.5));
        // xbox2RBumper.whenPressed(new IncrementCap());
        // xbox2LBumper.whenPressed(new DecrementCap());
        // xbox2Start.whenPressed(new ToggleCompressor());

        // xbox2RBumper.whileHeld(new ArcDrive2()); // Auto Hatch
        
    }

    public XboxController getXbox1() {
        return xbox1;
    }

    // public XboxController getXbox2() {
    //     return xbox2;
    // }
}
